"""empty message

Revision ID: 565f02f263df
Revises: 7663a944036d
Create Date: 2022-02-22 12:38:30.341234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '565f02f263df'
down_revision = '7663a944036d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website_link', sa.String(length=300), nullable=True))
    op.drop_column('venue', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_column('venue', 'website_link')
    # ### end Alembic commands ###
